before_install:
  # Install gem
  - gem update --system
  - gem install bundler
  
language: ruby

rvm:
  - 2.3.0
  - 2.3.7
  - 2.4.4
  - 2.5.1

script: bundle exec rspec

sudo: false

cache: bundler
