# Disable the default submodule logic, since we need to transform the paths
# from SSH -> HTTPS first.
# 
# See notes in `//test/ci/travis/before_install.inc.bash`
# 
git:
  submodules: false

before_install:
  - source ./test/ci/travis/before_install.inc.bash
  
language: ruby

rvm:
  - 2.3.0
  - 2.3.7
  - 2.4.4
  - 2.5.1

script: bundle exec rake

sudo: false

cache: bundler
