require 'nrser'

require_relative './refinements/object'
require_relative './refinements/string'
require_relative './refinements/array'
require_relative './refinements/hash'
require_relative './refinements/pathname'
require_relative './refinements/exception'
require_relative './refinements/binding'
require_relative './refinements/set'
require_relative './refinements/open_struct'
require_relative './refinements/enumerator'
